server:
  port: 8149
spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:fakerdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
