server:
  port: 8122

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:batchdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        generate_statistics: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
