server:
  port: 8138
spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:keycloakdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
