server:
  port: 8133

spring:
  application:
    name: 33-SpringAOP
  datasource:
    url: jdbc:h2:mem:aopdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
  threads:
    virtual:
      enabled: true

logging:
  level:
    com.example.aop: DEBUG
