server:
  port: 8106

spring:
  application:
    name: gateway-service
  threads:
    virtual:
      enabled: true

  # Default Resilience4j Configuration
resilience4j.circuitbreaker:
  instances:
    myCircuitBreaker:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      failureRateThreshold: 50
      waitDurationInOpenState: 5000
