spring:
  application:
    name: liquibase-demo
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate # Liquibase manages schema
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev

server:
  port: 8125
