spring:
  application:
    name: apache-poi-demo
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  threads:
    virtual:
      enabled: true

server:
  port: 8157
