server:
  port: 8130

spring:
  application:
    name: sentinel-demo
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:sentineldb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
