server:
  port: 8129

spring:
  application:
    name: resilience-service
  threads:
    virtual:
      enabled: true

management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers,ratelimiters,retry
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 2s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: true
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 3
        maxWaitDuration: 0s
  timelimiter:
    configs:
      default:
        timeoutDuration: 1s
        cancelRunningFuture: true
